// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "COVID Status",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "COVID Status",
            targets: ["AppModule"],
            teamIdentifier: "VWWZ7BR2NG",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/spacenation/swiftui-charts.git", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/swiftcsv/SwiftCSV.git", "0.6.1"..<"1.0.0"),
        .package(url: "https://github.com/groue/GRDB.swift.git", .exact("5.17.0"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Charts", package: "swiftui-charts"),
                .product(name: "SwiftCSV", package: "swiftcsv"),
                .product(name: "GRDB", package: "grdb.swift")
            ],
            path: "."
        )
    ]
)
